# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: Build

on:
  workflow_dispatch:
  push:
    paths:
      - 'src/**'
      - 'build.gradle'
      - '.github/workflows/build.yml'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml
    - name: Apply Cache
      uses: actions/cache@v3
      with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys:
            ${{ runner.os }}-gradle-
    - name: Chmod
      run: chmod +x ./gradlew 
    - name: Build
      run: ./gradlew build
    - name: Collect Artifact
      uses: actions/upload-artifact@v3
      with:
          name: Mod
          path: ./build/libs/*
